### ISSUE TITLE
Projects -->  Doc Sync

### ISSUE THREAD

**Issue by lkngtn** [1Hive/1Hive#36]
Should we adopt the pattern of putting documentation in project specific repos and syncing to the projects sections?

**Comment by burrrata** [comment]
I support that :)

**Comment by burrrata** [comment]
Here's some old notes on what that might look like.

<br>

### 1Hive Website Repo

In `https://github.com/1Hive/website/docs/contribute/`:
- moving `github.md` and `keybase.md` to a docs folder in the community/communications repo
- moving everything else describing the DAO membership/participation structure to a docs folder in the dao repo

In `https://github.com/1Hive/website/tree/master/docs/projects`:
- linking to an `overview` page in the docs section of each project's repo rather than having it hard coded into the website

In `https://github.com/1Hive/website/tree/master/docs/wiki`:
- This section can stay the same, but if more projects roll their own docs we can start linking in rather than maintaining hard copies ourselves

**Comment by yeqbfgxjiq** [comment]
I think that's generally a solid way to do things. Right now I'm building the docs for Redemptions in that repo and then we can sync it wherever we want. 

Just created a branch that has a basic sync script and submitted a PR
- https://github.com/1Hive/website/pull/44

Also, as I'm going through and spell checking all the docs (tired of looking at that Issue in list), and I think it makes sense to set up syncing for the Dandelion Org apps. Since the READMEs are going to be focused on developers, thinking it makes sense to create an "overview" doc that just gives a high level description of the app, it's intended usecase, and where to learn more (user guide, technical docs, repo, etc...)

**Comment by yeqbfgxjiq** [comment]
Looks like we're doing this so I'm going to close this Issue
